# Generated by Django 4.1.3 on 2022-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='14.jpg', upload_to='image_blog/%Y', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
