# Generated by Django 4.1.3 on 2022-12-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0005_alter_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='a_blog.blog', verbose_name='коментарии'),
        ),
    ]
