# Generated by Django 4.1.3 on 2022-12-23 19:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0007_alter_blog_text_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text_comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
