# Generated by Django 4.1.3 on 2022-12-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0014_alter_comments_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
    ]
